# Option 1: Using AWS Access Keys (not recommended for production)
# For production, use IRSA (IAM Roles for Service Accounts) - see option 2
apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
stringData:
  AVP_TYPE: "awssecretsmanager"
  AWS_REGION: "ap-south-1"  # Change to your region
  AWS_ACCESS_KEY_ID: "AKIAXXXXXXXXXXXXXXXX"
  AWS_SECRET_ACCESS_KEY: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
