# Example Kubernetes Secret that references AWS Secrets Manager
# This file goes in your Git repo that ArgoCD manages
#
# Prerequisites:
# 1. Create a secret in AWS Secrets Manager named "myapp/prod/credentials" with JSON:
#    {
#      "username": "admin",
#      "password": "supersecret123",
#      "api_key": "sk-xxxxxxxxxxxx"
#    }

---
# Option 1: Using annotation for path (recommended for multiple keys from same secret)
apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
  namespace: default
  annotations:
    avp.kubernetes.io/path: "myapp/prod/credentials"
type: Opaque
stringData:
  username: <username>
  password: <password>
  api-key: <api_key>

---
# Option 2: Using inline path (good for single values or mixed sources)
apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret-inline
  namespace: default
type: Opaque
stringData:
  username: <path:myapp/prod/credentials#username>
  password: <path:myapp/prod/credentials#password>
  api-key: <path:myapp/prod/credentials#api_key>

---
# Option 3: Using full ARN (required for cross-account access)
apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret-arn
  namespace: default
type: Opaque
stringData:
  password: <path:arn:aws:secretsmanager:ap-south-1:123456789012:secret:myapp/prod/credentials#password>

---
# Option 4: Using specific version
apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret-versioned
  namespace: default
type: Opaque
stringData:
  # Using version stage
  current-password: <path:myapp/prod/credentials#password#AWSCURRENT>
  previous-password: <path:myapp/prod/credentials#password#AWSPREVIOUS>
