# Default values for metrics-logs-python-app.

replicaCount: 1

image:
  repository: rahees9983/python-log-metrics-app-grafan
  tag: v1
  pullPolicy: IfNotPresent

service:
  enabled: true
  type: NodePort
  port: 5000
  targetPort: 5000
  nodePort: 30009

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

nodeSelector: {}

tolerations: []

affinity: {}

