apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: frontend-service
  namespace: default
spec:
  ports:
  - nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend
  type: NodePort
