apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: frontend-v2
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
        version: v2
    spec:
      containers:
      - image: rahees9983/deployment-strategy-app:v2
        imagePullPolicy: IfNotPresent
        name: webapp-color

