apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: myapp
    tier: frontend
  name: frontend
  namespace: default
spec:
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      containers:
      - image: rahees9983/deployment-strategy-app:v1
        imagePullPolicy: IfNotPresent
        name: webapp-color

