apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-controller
  template:
    metadata:
      labels:
        app: game-controller
    spec:
      serviceAccountName: game-controller
      containers:
      - name: controller
        image: your-registry/game-controller:latest

