apiVersion: v1
kind: ServiceAccount
metadata:
  name: game-controller

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: game-controller
rules:
- apiGroups: ["mygames.com"]
  resources: ["games"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: game-controller
subjects:
- kind: ServiceAccount
  name: game-controller
  namespace: default
roleRef:
  kind: ClusterRole
  name: game-controller
  apiGroup: rbac.authorization.k8s.io

