# Service for Canary Rollout
# Argo Rollouts manages traffic splitting automatically

apiVersion: v1
kind: Service
metadata:
  name: myapp-canary-svc
  namespace: default
  labels:
    app: myapp-canary
spec:
  type: LoadBalancer #ClusterIP
  selector:
    app: myapp-canary
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
