# Secret for HashiCorp Vault backend
apiVersion: v1
kind: Secret
metadata:
  name: avp-vault-credentials
  namespace: argocd
type: Opaque
stringData:
  VAULT_ADDR: "http://YOUR-VAULT-IP:8200"
  VAULT_TOKEN: "hvs.REPLACE-WITH-YOUR-VAULT-TOKEN"
  AVP_TYPE: "vault"
  AVP_AUTH_TYPE: "token"
