# This file goes in your Git repository
# ArgoCD Vault Plugin will replace the placeholders with actual values from AWS Secrets Manager
#
# AWS Secret Manager secret name: myapp/prod/credentials
# AWS Secret Manager secret value (JSON):
# {
#   "username": "admin",
#   "password": "MySecureP@ssw0rd",
#   "api_key": "sk-1234567890abcdef"
# }

---
# Option 1: Using annotation (recommended when all keys come from same secret)
apiVersion: v1
kind: Secret
metadata:
  name: myapp-credentials
  namespace: default
  annotations:
    avp.kubernetes.io/path: "myapp/prod/credentials"
type: Opaque
stringData:
  USERNAME: <username>
  PASSWORD: <password>
  API_KEY: <api_key>

---
# Option 2: Using inline path syntax
apiVersion: v1
kind: Secret
metadata:
  name: myapp-credentials-inline
  namespace: default
type: Opaque
stringData:
  USERNAME: <path:myapp/prod/credentials#username>
  PASSWORD: <path:myapp/prod/credentials#password>
  API_KEY: <path:myapp/prod/credentials#api_key>
