# Patch for argocd-repo-server deployment
# Apply with: kubectl patch deployment argocd-repo-server -n argocd --patch-file repo-server-patch.yaml
#
# OR apply the full deployment below with: kubectl apply -f repo-server-patch.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      containers:
        # Keep the existing repo-server container as-is
        # Add the AVP sidecar container below
        - name: avp
          command: [/var/run/argocd/argocd-cmp-server]
          image: quay.io/argoproj/argocd:v3.2.2
          envFrom:
            - secretRef:
                name: argocd-vault-plugin-credentials
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /tmp
              name: tmp
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: avp.yaml
              name: cmp-plugin
            - mountPath: /usr/local/bin/argocd-vault-plugin
              name: custom-tools
              subPath: argocd-vault-plugin
      volumes:
        # Add this volume (other volumes already exist)
        - name: cmp-plugin
          configMap:
            name: cmp-plugin
