apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: "kv/data/app"
  name: app-secret
  namespace: default
type: Opaque
stringData:
  password: <password>
  token: <token>
  username: <username>

VAULT_ADDR=http://YOUR-VAULT-IP:8200/
VAULT_TOKEN=hvs.REPLACE-WITH-YOUR-VAULT-TOKEN
AVP_TYPE=vault
AVP_AUTH_TYPE=token

argocd-repo-server
argocd-cm


https://argocd-vault-plugin.readthedocs.io/en/stable/installation/#initcontainer-and-configuration-via-argocd-cm-configmap

curl -Lo argocd-vault-plugin https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v1.18.1/argocd-vault-plugin_1.18.1_linux_amd64

chmod +x argocd-vault-plugin

mv argocd-vault-plugin /usr/local/bin


apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: create-secrets
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: argocd/SyncWaves
    repoURL: https://github.com/Rahees9983/devops-batch1.git
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin
      env:
        - name: VAULT_ADDR
          value: http://YOUR-VAULT-IP:8200
        - name: VAULT_TOKEN
          value: hvs.REPLACE-WITH-YOUR-VAULT-TOKEN
        - name: AVP_TYPE
          value: vault
        - name: AVP_AUTH_TYPE
          value: token
  sources: []
  project: default
