version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: curd         # This will create the 'curd' database
      MYSQL_USER: u1               # Creates the user 'u1'
      MYSQL_PASSWORD: root         # Password for 'u1'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Persist MySQL data
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the SQL script

  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: u1
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: curd
    depends_on:
      - mysql

volumes:
  mysql_data:

