# Wave 0: PreSync Hook - WILL FAIL ON PURPOSE
apiVersion: batch/v1
kind: Job
metadata:
  name: vm-metrics-app-presync
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "0"
spec:
  template:
    spec:
      containers:
      - name: presync
        image: busybox
        command: 
        - sh
        - -c
        - |
          echo "============================================"
          echo "       PRESYNC HOOK - WAVE 0               "
          echo "============================================"
          echo ""
          echo "Time: $(date)"
          echo ""
          echo "Step 1: Checking database connection..."
          sleep 10
          echo "Step 2: Running database migrations..."
          sleep 10
          echo ""
          echo "ERROR: Database migration failed!"
          echo "============================================"
          exit 1
      restartPolicy: Never
  backoffLimit: 0
---
# Wave 1: Service (won't be created - presync fails)
apiVersion: v1
kind: Service
metadata:
  name: vm-metrics-app-service
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    nodePort: 30002
  selector:
    app: vm-metrics-app
---
# Wave 2: Deployment (won't be created - presync fails)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-metrics-app
  labels:
    app: vm-metrics-app
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vm-metrics-app
  template:
    metadata:
      labels:
        app: vm-metrics-app
    spec:
      containers:
      - name: vm-metrics-app
        image: rahees9983/vm-metrics-app:with-gui
        ports:
        - containerPort: 5000
---
# Wave 3: PostSync Hook (won't run - presync fails)
apiVersion: batch/v1
kind: Job
metadata:
  name: vm-metrics-app-postsync
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "3"
spec:
  template:
    spec:
      containers:
      - name: postsync
        image: busybox
        command:
        - sh
        - -c
        - |
          echo "============================================"
          echo "       POSTSYNC HOOK - WAVE 3              "
          echo "============================================"
          echo "This should NOT run if PreSync fails!"
      restartPolicy: Never
  backoffLimit: 1
---
# SyncFail Hook - THIS WILL RUN!
apiVersion: batch/v1
kind: Job
metadata:
  name: vm-metrics-app-syncfail
  annotations:
    argocd.argoproj.io/hook: SyncFail
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: syncfail
        image: busybox
        command:
        - sh
        - -c
        - |
          echo "============================================"
          echo "       SYNCFAIL HOOK TRIGGERED!            "
          echo "============================================"
          echo ""
          echo "Time: $(date)"
          echo ""
          echo "Step 1: Capturing error logs..."
          sleep 10
          echo "Step 2: Sending Slack alert to team..."
          sleep 10
          echo "Step 3: Creating JIRA incident ticket..."
          sleep 10
          echo "Step 4: Rolling back changes..."
          sleep 10
          echo ""
          echo "Incident response completed!"
          echo "============================================"
      restartPolicy: Never
  backoffLimit: 1