# ============================================================
# RBAC for ArgoCD Repo Server to use Kubernetes Auth
# ============================================================
# This allows the repo-server to authenticate with Vault using
# its service account token
# ============================================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-repo-server
  namespace: argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-repo-server-token-review
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: argocd-repo-server
    namespace: argocd
