# ============================================================
# ArgoCD Vault Plugin - Configuration Secret
# ============================================================
# This secret contains the configuration for AVP to connect to Vault
# ============================================================

apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
stringData:
  # Vault address (use internal K8s service DNS)
  VAULT_ADDR: "http://vault.vault.svc.cluster.local:8200"

  # Authentication type: token, k8s, approle
  AVP_TYPE: "vault"
  AVP_AUTH_TYPE: "k8s"

  # For Kubernetes auth (recommended)
  AVP_K8S_MOUNT_PATH: "auth/kubernetes"
  AVP_K8S_ROLE: "argocd"

  # For Token auth (dev/testing only)
  # AVP_AUTH_TYPE: "token"
  # AVP_TOKEN: "root"

  # For AppRole auth
  # AVP_AUTH_TYPE: "approle"
  # AVP_ROLE_ID: "your-role-id"
  # AVP_SECRET_ID: "your-secret-id"

  # KV version (1 or 2)
  AVP_KV_VERSION: "2"
---
# Alternative: Token-based auth for development
apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-plugin-credentials-dev
  namespace: argocd
type: Opaque
stringData:
  VAULT_ADDR: "http://vault.vault.svc.cluster.local:8200"
  AVP_TYPE: "vault"
  AVP_AUTH_TYPE: "token"
  VAULT_TOKEN: "root"
  AVP_KV_VERSION: "2"
