# ServiceAccount and RBAC for running workflows in the default namespace
# This allows you to run workflows in the 'default' namespace

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflow
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-role
  namespace: default
rules:
  # Pod operations
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "patch", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "watch"]
  # Workflow operations
  - apiGroups: ["argoproj.io"]
    resources: ["workflows"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
  # Secrets for artifacts
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  # ConfigMaps
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflow-role
subjects:
  - kind: ServiceAccount
    name: argo-workflow
    namespace: default
