# kind: Secret
# apiVersion: v1
# metadata:
#   name: example-secret
#   annotations:
#     avp.kubernetes.io/path: "secret/myapp/config"
# type: Opaque
# stringData:
#   sample-secret: <username>

# Using avp.kubernetes.io/path  Annotation
# We are setting avp.kubernetes.io/path  to tell the plugin exactly where to find data
# https://argocd-vault-plugin.readthedocs.io/en/stable/howitworks/#generic-placeholders
# kind: Secret
# apiVersion: v1
# metadata:
#   name: example-annotation
#   namespace: argocd
#   annotations:
#     avp.kubernetes.io/path: "secret/myapp/config"
# type: Opaque
# data:
#   username: <username>
#   # password: <password>

apiVersion: v1
kind: Secret
metadata:
  name: my-application-secret
type: Opaque
stringData:
  username: <path:kv/data/myapp/config#username>
  password: <path:kv/data/myapp/config#password>
