# Converted Rollout - Canary Strategy
# Changes from Deployment:
#   1. apiVersion: apps/v1 → argoproj.io/v1alpha1
#   2. kind: Deployment → Rollout
#   3. Added strategy.canary section with steps

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: myapp-canary
  namespace: default
  labels:
    app: myapp-canary
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myapp-canary
  template:
    metadata:
      labels:
        app: myapp-canary
    spec:
      containers:
      - name: app
        image: rahees9983/deployment-strategy-app:v1
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: VERSION
          value: "v1"
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}           # Manual gate - wait for promotion
      - setWeight: 40
      - pause: {duration: 30s}
      - setWeight: 60
      - pause: {duration: 30s}
      - setWeight: 80
      - pause: {duration: 30s}
      # 100% happens automatically after all steps
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-canary-svc
  namespace: default
  labels:
    app: myapp-canary
spec:
  type: LoadBalancer
  selector:
    app: myapp-canary
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
