# ============================================================
# Example 1: Simple Secret with AVP Placeholders
# ============================================================
# This secret uses AVP path annotation to fetch all keys
# from a single Vault path
#
# Vault secret should be created at: secret/myapp/config
# with keys: username, password, api_key
# ============================================================

apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
  namespace: default
  annotations:
    # This annotation tells AVP where to fetch secrets from
    avp.kubernetes.io/path: "secret/data/myapp/config"
type: Opaque
stringData:
  # AVP will replace <key> with the value from Vault
  username: <username>
  password: <password>
  api_key: <api_key>
---
# Alternative: Inline path syntax (more flexible)
apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret-inline
  namespace: default
type: Opaque
stringData:
  # Full path syntax - can mix secrets from different paths
  db-password: <path:secret/data/myapp/database#password>
  api-key: <path:secret/data/myapp/api#key>
  jwt-secret: <path:secret/data/myapp/auth#jwt_secret>
