# ServiceMonitors for ArgoCD (argo-cd chart v9.3.0)
# Apply AFTER running: helm upgrade argocd argo/argo-cd -n argocd -f argocd-metrics-values.yaml

---
# ArgoCD Application Controller Metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-application-controller
  namespace: monitoring
  labels:
    release: my-release
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-metrics
      app.kubernetes.io/component: application-controller
  endpoints:
    - port: http-metrics
      interval: 30s

---
# ArgoCD Server Metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-server
  namespace: monitoring
  labels:
    release: my-release
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server-metrics
      app.kubernetes.io/component: server
  endpoints:
    - port: http-metrics
      interval: 30s

---
# ArgoCD Repo Server Metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-repo-server
  namespace: monitoring
  labels:
    release: my-release
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server-metrics
      app.kubernetes.io/component: repo-server
  endpoints:
    - port: http-metrics
      interval: 30s

---
# ArgoCD ApplicationSet Controller Metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-applicationset-controller
  namespace: monitoring
  labels:
    release: my-release
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-metrics
      app.kubernetes.io/component: applicationset-controller
  endpoints:
    - port: http-metrics
      interval: 30s

---
# ArgoCD Redis Metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-redis
  namespace: monitoring
  labels:
    release: my-release
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-redis
      app.kubernetes.io/component: redis
  endpoints:
    - port: http-metrics
      interval: 30s

---
# ArgoCD Notifications Controller Metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-notifications-controller
  namespace: monitoring
  labels:
    release: my-release
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-metrics
      app.kubernetes.io/component: notifications-controller
  endpoints:
    - port: http-metrics
      interval: 30s

---
# ArgoCD Dex Server Metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-dex-server
  namespace: monitoring
  labels:
    release: my-release
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-dex-server
      app.kubernetes.io/component: dex-server
  endpoints:
    - port: http-metrics
      interval: 30s