---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-logs-python-app
  labels:
    app: metrics-logs-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-logs-python-app
  template:
    metadata:
      labels:
        app: metrics-logs-python-app
    spec:
      containers:
        - name: metrics-logs-python-app
          image: rahees9983/python-log-metrics-app-grafan:v1
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-logs-python-app
spec:
  type: NodePort 
  ports:
    - port: 5000     
      targetPort: 5000  
      nodePort: 30009
  selector:
    app: metrics-logs-python-app
