apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: "kv/data/app"
  name: app-secret
  namespace: default
type: Opaque
stringData:
  password: <password>
  token: <token>
  username: <username>
